steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/distance-connect:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/distance-connect:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "distance-connect"
      - "--image"
      - "gcr.io/$PROJECT_ID/distance-connect:$COMMIT_SHA"
      - "--region"
      - "asia-south2"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      

images:
  - "gcr.io/$PROJECT_ID/distance-connect:$COMMIT_SHA"

# These substitution variables need to be defined in your Cloud Build trigger
# or secrets manager for sensitive values
substitutions:
  _DATABASE_URL: ""
  _UPSTASH_REDIS_REST_URL: ""
  _UPSTASH_REDIS_REST_TOKEN: ""
  _NEXT_PUBLIC_BASE_URL: ""
  _NEXT_PUBLIC_GEMINI_API_KEY: ""
  _RESEND_API_KEY: ""
  _EMAIL_HOST: ""
  _EMAIL_PORT: ""
  _EMAIL_USER: ""
  _EMAIL_PASSWORD: ""
  _EMAIL_FROM: ""
  _SUPPORT_EMAIL: ""
  _AUTH0_SECRET: ""
  _APP_BASE_URL: ""
  _AUTH0_DOMAIN: ""
  _AUTH0_CLIENT_ID: ""
  _AUTH0_CLIENT_SECRET: ""
  _GOOGLE_SERVICE_ACCOUNT_EMAIL: ""
  _GOOGLE_PRIVATE_KEY: ""
  _ABLY_API_KEY: ""
  _GCP_PROJECT_ID: ""
  _GCP_CHAT_IMAGE_BUCKET_NAME: ""
  _GCP_CLIENT_EMAIL: ""
  _GCP_PRIVATE_KEY: ""
  _NODE_ENV: ""
  _SKIP_ENV_VALIDATION: ""
  _CF_SPACE_ID: ""
  _CF_DELIVERY_ACCESS_TOKEN: ""   






